apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: LearnCP4I
  owner: LearnCP4I
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/LearnCP4I/multi-tenancy-gitops-apps.git
