apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBrzNgX1jTfArzBFgKMx09qMy/4///V7i0Ur99fB/ZNRQg2TlMcTondszFQcylK2EGwaggzqGsgZStFG3Jl5un1fg+R/Ep+FSrsii9VdutqTt+LjdlarBLPS5IAxA249ftOtFf9LaYDBE3/aaHaYN1EWRQhTsccOtBjCEolkUmDp0fiQLVyexa1r6MQP61Ra2fRFTujQVrReABwb2d3N9X1uC+iH5Sdt3VceeH/zQjdMV110uXI5sHgZgwds33gKJxkDT9cLEjUG4ZWNl4T0El3LD14tBc3bZ5ka+u5u0orUtcO3wy4ZjDesvrHmVH4MGA5wQon0HDojzi+chGrUaHmRXj9dOvk02YKyTLXa+3IvErqKXfR+qtDuNmXiORGm0sZRAITkxIPkZePzbnzubleM3WnkIWE43KRm7rIYVjSInHWIzae1XDIt3Mycz6KPPjxmwdVTfWFiRKX9oXGtjfeTmFkG+U+Kr/YYrsI6OlZQ1uKP4crE20saDK++H7bCV4eJ3vap6x/DkOw0MKc0eLT6iD42NV8PKaUpY5WX4CuBcnQlWmeznfToRqdl6tzue4vY+grUXhDlXAbw+8GTfxxeEOtO+Bm6gdhVphDc0XqdSTgt8E3Wy69UqPh87Wuxucfbzk2LujYZ6XiYfmeVw9MORb4tAdN8yS7GnSSVST8H6svpRGUKnd1jxRG3jbcNzwcoRj08ZmM1fuMkyy73pCUe1UmvlwLd1+8vpzIpUXTa5XiHSTr2eINFGtuzjcZGXRsKNLPSMWLArC9mZT5n8vsGyatn499vT0jag4iD//PmFJZocxu3AwCaCVSWyKay1hFkeymYvj9LSN1Abq7mzmgj7TvJnBWxsmPBTPFs5PW59AAxMlXE/KNhTccDwWgYzlbGi3lg87Z+6cYODk/22OIVHqhMik2inIBPDXIt3eYFcSS6ZLc9xjT3xXsweLK47s=
    IBM_ENTITLED_REGISTRY_USER: AgBieJH9jksPI6xepFvoQVmFwAdg0OKdHdcvpyeDkkb3vUUHDdZbbCPInwbF9yMQogg/GPbb1op0It1kNzwvDf2Zu92EYMH4eFGuiU6gip6LNAfmufrj8OYVseHULLApHWz/wiZ7vtmJj0WeAGWQB5+yuAqkwnRX8JtXb72XvxDqMSK5u8NVThS2OdPxRI1dBSvDfPAvqeOeFILhIEWhuFmcShWTqd3typBG+Pngq251tAnIyuhsa15a/EnsnVutYk4jV9Zd3EV4aFh6lHql1Fy45ltqZWeUUJRGCQIgtKYHlaw8dxg5X2SpALk/J1GwQOswBIjdueNV/HiqE7RvcWJbVjBffdGa8RLwgt4uO4rh9/XJmwWeinHXR6e58voVbMwTGAr/iBLCqI6BfcW6uYBoyHeKYafNnAiqNkonXVfnWREPYVyx/2xIYRKsGZffDMepVHoM6wa5Zj4pobC1rAEEsuX0LtaioSeHzokxY6BY6LcO7PVCs6RMrF9AuPcvVuRWeyxEGddqVSQY2I9BcTl/zyFLXUARif23b7LCzR5ztNpjZWwEM/be3GNzCr3Kjprn97EZxW4/bIW8QfRaviRoh4VdYGIKLMhXjDOUknM856B+mspSh0/3WqwSyMT2arg2A0+skYEWnp+7+Z6mthAIWh/PjP4NAMhKhA4Ai5Ro1pYsh4tXXFqFLIBculZtvo6yog==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

